import type { Monaco } from '@monaco-editor/react';

export const MONACO_THEME_MAP: Record<string, string> = {
  noir:     'hex-noir',
  graphite: 'hex-graphite',
  mocha:    'hex-mocha',
  light:    'hex-light',
};

const DARK_RULES = [
  { token: 'keyword.gql',   foreground: 'a78bfa' },
  { token: 'type.gql',      foreground: 'e879f9' },
  { token: 'variable.gql',  foreground: 'fde047' },
  { token: 'string.gql',    foreground: '6ee7b7' },
  { token: 'number.gql',    foreground: 'fb923c' },
  { token: 'comment.gql',   foreground: '4a4a72', fontStyle: 'italic' },
  { token: 'operator.gql',  foreground: '94a3b8' },
  { token: 'delimiter.gql', foreground: '94a3b8' },
  { token: 'string.key.json',            foreground: 'a78bfa' },
  { token: 'string.value.json',          foreground: '6ee7b7' },
  { token: 'number.json',                foreground: 'fb923c' },
  { token: 'keyword.json',               foreground: 'f472b6' },
  { token: 'delimiter.array.json',       foreground: '94a3b8' },
  { token: 'delimiter.bracket.json',     foreground: '94a3b8' },
  { token: 'delimiter.colon.json',       foreground: '94a3b8' },
  { token: 'delimiter.comma.json',       foreground: '94a3b8' },
  { token: 'keyword',   foreground: 'a78bfa' },
  { token: 'string',    foreground: '6ee7b7' },
  { token: 'number',    foreground: 'fb923c' },
  { token: 'comment',   foreground: '4a4a72', fontStyle: 'italic' },
  { token: 'variable',  foreground: 'fde047' },
  { token: 'type',      foreground: 'e879f9' },
  { token: 'operator',  foreground: '94a3b8' },
  { token: 'delimiter', foreground: '94a3b8' },
] as const;

const LIGHT_RULES = [
  { token: 'keyword.gql',   foreground: '6d28d9' },
  { token: 'type.gql',      foreground: 'a21caf' },
  { token: 'variable.gql',  foreground: '92400e' },
  { token: 'string.gql',    foreground: '115e59' },
  { token: 'number.gql',    foreground: '9a3412' },
  { token: 'comment.gql',   foreground: 'a8a29e', fontStyle: 'italic' },
  { token: 'operator.gql',  foreground: '78716c' },
  { token: 'delimiter.gql', foreground: '78716c' },
  { token: 'string.key.json',            foreground: '6d28d9' },
  { token: 'string.value.json',          foreground: '115e59' },
  { token: 'number.json',                foreground: '9a3412' },
  { token: 'keyword.json',               foreground: '9d174d' },
  { token: 'delimiter.array.json',       foreground: '78716c' },
  { token: 'delimiter.bracket.json',     foreground: '78716c' },
  { token: 'delimiter.colon.json',       foreground: '78716c' },
  { token: 'delimiter.comma.json',       foreground: '78716c' },
  { token: 'keyword',   foreground: '6d28d9' },
  { token: 'string',    foreground: '115e59' },
  { token: 'number',    foreground: '9a3412' },
  { token: 'comment',   foreground: 'a8a29e', fontStyle: 'italic' },
  { token: 'variable',  foreground: '92400e' },
  { token: 'type',      foreground: 'a21caf' },
  { token: 'operator',  foreground: '78716c' },
  { token: 'delimiter', foreground: '78716c' },
] as const;

export function registerAllThemes(monaco: Monaco) {
  monaco.editor.defineTheme('hex-noir', {
    base: 'vs-dark',
    inherit: true,
    rules: [...DARK_RULES],
    colors: {
      'editor.background':              '#0c0c1d',
      'editor.foreground':              '#e2e8f0',
      'editor.lineHighlightBackground': '#13132a',
      'editor.selectionBackground':     '#3d2d7a80',
      'editor.inactiveSelectionBackground': '#3d2d7a40',
      'editor.selectionHighlightBackground': '#3d2d7a50',
      'editor.wordHighlightBackground': '#2d1f5e80',
      'editor.findMatchBackground':     '#7c3aed50',
      'editor.findMatchHighlightBackground': '#7c3aed30',
      'editorLineNumber.foreground':       '#2e2e5a',
      'editorLineNumber.activeForeground': '#7c7cbc',
      'editorCursor.foreground': '#a78bfa',
      'editorIndentGuide.background1':       '#1c1c38',
      'editorIndentGuide.activeBackground1': '#3d3d6b',
      'editorBracketMatch.background': '#3d2d7a50',
      'editorBracketMatch.border':     '#7c3aed',
      'editorSuggestWidget.background':          '#0c0c1d',
      'editorSuggestWidget.border':              '#1c1c38',
      'editorSuggestWidget.foreground':          '#e2e8f0',
      'editorSuggestWidget.selectedBackground':  '#1c1c38',
      'editorSuggestWidget.selectedForeground':  '#f0f0ff',
      'editorSuggestWidget.highlightForeground': '#a78bfa',
      'editorSuggestWidget.focusHighlightForeground': '#c084fc',
      'editorHoverWidget.background': '#0c0c1d',
      'editorHoverWidget.border':     '#1c1c38',
      'editorHoverWidget.foreground': '#e2e8f0',
      'scrollbarSlider.background':       '#ffffff18',
      'scrollbarSlider.hoverBackground':  '#ffffff28',
      'scrollbarSlider.activeBackground': '#ffffff38',
      'editorGutter.background':            '#0c0c1d',
      'editorOverviewRuler.border':         '#1c1c38',
      'editorOverviewRuler.findMatchForeground': '#7c3aed',
    },
  });

  monaco.editor.defineTheme('hex-graphite', {
    base: 'vs-dark',
    inherit: true,
    rules: [...DARK_RULES],
    colors: {
      'editor.background':              '#111111',
      'editor.foreground':              '#e2e8f0',
      'editor.lineHighlightBackground': '#1e1e20',
      'editor.selectionBackground':     '#3d2d7a80',
      'editor.inactiveSelectionBackground': '#3d2d7a40',
      'editor.selectionHighlightBackground': '#3d2d7a50',
      'editor.wordHighlightBackground': '#2d1f5e80',
      'editor.findMatchBackground':     '#7c3aed50',
      'editor.findMatchHighlightBackground': '#7c3aed30',
      'editorLineNumber.foreground':       '#333336',
      'editorLineNumber.activeForeground': '#6e6e7a',
      'editorCursor.foreground': '#a78bfa',
      'editorIndentGuide.background1':       '#272727',
      'editorIndentGuide.activeBackground1': '#3e3e3e',
      'editorBracketMatch.background': '#3d2d7a50',
      'editorBracketMatch.border':     '#7c3aed',
      'editorSuggestWidget.background':          '#111111',
      'editorSuggestWidget.border':              '#2a2a2e',
      'editorSuggestWidget.foreground':          '#e2e8f0',
      'editorSuggestWidget.selectedBackground':  '#2a2a2e',
      'editorSuggestWidget.selectedForeground':  '#f0f0ff',
      'editorSuggestWidget.highlightForeground': '#a78bfa',
      'editorSuggestWidget.focusHighlightForeground': '#c084fc',
      'editorHoverWidget.background': '#111111',
      'editorHoverWidget.border':     '#2a2a2e',
      'editorHoverWidget.foreground': '#e2e8f0',
      'scrollbarSlider.background':       '#ffffff18',
      'scrollbarSlider.hoverBackground':  '#ffffff28',
      'scrollbarSlider.activeBackground': '#ffffff38',
      'editorGutter.background':            '#111111',
      'editorOverviewRuler.border':         '#2a2a2e',
      'editorOverviewRuler.findMatchForeground': '#7c3aed',
    },
  });

  monaco.editor.defineTheme('hex-mocha', {
    base: 'vs-dark',
    inherit: true,
    rules: [...DARK_RULES],
    colors: {
      'editor.background':              '#1a1613',
      'editor.foreground':              '#e2e8f0',
      'editor.lineHighlightBackground': '#252019',
      'editor.selectionBackground':     '#3d2d7a80',
      'editor.inactiveSelectionBackground': '#3d2d7a40',
      'editor.selectionHighlightBackground': '#3d2d7a50',
      'editor.wordHighlightBackground': '#2d1f5e80',
      'editor.findMatchBackground':     '#7c3aed50',
      'editor.findMatchHighlightBackground': '#7c3aed30',
      'editorLineNumber.foreground':       '#3a3028',
      'editorLineNumber.activeForeground': '#7a6858',
      'editorCursor.foreground': '#a78bfa',
      'editorIndentGuide.background1':       '#332b23',
      'editorIndentGuide.activeBackground1': '#473c30',
      'editorBracketMatch.background': '#3d2d7a50',
      'editorBracketMatch.border':     '#7c3aed',
      'editorSuggestWidget.background':          '#1a1613',
      'editorSuggestWidget.border':              '#332b23',
      'editorSuggestWidget.foreground':          '#e2e8f0',
      'editorSuggestWidget.selectedBackground':  '#332b23',
      'editorSuggestWidget.selectedForeground':  '#f0f0ff',
      'editorSuggestWidget.highlightForeground': '#a78bfa',
      'editorSuggestWidget.focusHighlightForeground': '#c084fc',
      'editorHoverWidget.background': '#1a1613',
      'editorHoverWidget.border':     '#332b23',
      'editorHoverWidget.foreground': '#e2e8f0',
      'scrollbarSlider.background':       '#ffffff18',
      'scrollbarSlider.hoverBackground':  '#ffffff28',
      'scrollbarSlider.activeBackground': '#ffffff38',
      'editorGutter.background':            '#1a1613',
      'editorOverviewRuler.border':         '#332b23',
      'editorOverviewRuler.findMatchForeground': '#7c3aed',
    },
  });

  monaco.editor.defineTheme('hex-light', {
    base: 'vs',
    inherit: true,
    rules: [...LIGHT_RULES],
    colors: {
      'editor.background':              '#faf9f7',
      'editor.foreground':              '#1c1917',
      'editor.lineHighlightBackground': '#f0ece8',
      'editor.selectionBackground':     '#ddd6fe80',
      'editor.inactiveSelectionBackground': '#ddd6fe40',
      'editor.selectionHighlightBackground': '#ddd6fe50',
      'editor.wordHighlightBackground': '#ede9fe80',
      'editor.findMatchBackground':     '#7c3aed30',
      'editor.findMatchHighlightBackground': '#7c3aed18',
      'editorLineNumber.foreground':       '#c4b8b0',
      'editorLineNumber.activeForeground': '#78716c',
      'editorCursor.foreground': '#6d28d9',
      'editorIndentGuide.background1':       '#e8e4e0',
      'editorIndentGuide.activeBackground1': '#d5cfc8',
      'editorBracketMatch.background': '#ddd6fe80',
      'editorBracketMatch.border':     '#6d28d9',
      'editorSuggestWidget.background':          '#faf9f7',
      'editorSuggestWidget.border':              '#d5cfc8',
      'editorSuggestWidget.foreground':          '#1c1917',
      'editorSuggestWidget.selectedBackground':  '#ece8e3',
      'editorSuggestWidget.selectedForeground':  '#0c0a09',
      'editorSuggestWidget.highlightForeground': '#6d28d9',
      'editorSuggestWidget.focusHighlightForeground': '#7c3aed',
      'editorHoverWidget.background': '#faf9f7',
      'editorHoverWidget.border':     '#d5cfc8',
      'editorHoverWidget.foreground': '#1c1917',
      'scrollbarSlider.background':       '#00000015',
      'scrollbarSlider.hoverBackground':  '#00000025',
      'scrollbarSlider.activeBackground': '#00000035',
      'editorGutter.background':            '#faf9f7',
      'editorOverviewRuler.border':         '#d5cfc8',
      'editorOverviewRuler.findMatchForeground': '#6d28d9',
    },
  });
}
